apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docker-coffee
  name: docker-coffee-scheduler
  labels:
    app: docker-coffee-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-coffee-scheduler
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-coffee-scheduler
    spec:
      containers:
      - name: docker-coffee-scheduler
        image: christiaanderidder/docker-coffee-scheduler
        imagePullPolicy: Always
        resources: {}
