apiVersion: v1
kind: Service
metadata:
  namespace: docker-coffee
  name: docker-coffee-mssql
  labels:
    app: docker-coffee-mssql
spec:
  ports:
  - name: "mssql"
    port: 1433
    targetPort: 1433
  selector:
    app: docker-coffee-mssql
