apiVersion: v1
kind: Service
metadata:
  namespace: docker-coffee
  name: docker-coffee-api
  labels:
    app: docker-coffee-api
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: docker-coffee-api
