apiVersion: v1
kind: Service
metadata:
  namespace: docker-coffee
  name: docker-coffee-rabbitmq
  labels:
    app: docker-coffee-rabbitmq
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 15672
  - name: "amqp"
    port: 5672
    targetPort: 5672
  selector:
    app: docker-coffee-rabbitmq
